# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_SUNXI) += sun20i-d1-nezha.dtb
dtb-$(CONFIG_ARCH_SUNXI) += sun20i-d1-lichee-rv.dtb
dtb-$(CONFIG_ARCH_SUNXI) += sun20i-d1-lichee-rv-dock.dtb
dtb-$(CONFIG_ARCH_SUNXI) += sun20i-d1-nezha-1g.dtb
dtb-$(CONFIG_ARCH_SUNXI) += sun20i-d1-nezha-2g.dtb
dtb-$(CONFIG_ARCH_SUNXI) += sun20i-d1-nezha-512m.dtb
